# Generated by Django 4.0.6 on 2022-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('one', 'two'), ('three', 'four')], max_length=256)),
                ('rank', models.BigIntegerField()),
                ('question_english', models.CharField(max_length=500)),
                ('question_arabic', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
