# Generated by Django 4.0.6 on 2022-08-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0002_question_delete_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_arabic',
            new_name='asnwer_choice_one_arabic_الإجابة_الأولى_عربى',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_english',
            new_name='asnwer_choice_one_english_الإجابة_الأولى_انجليزي',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='rank',
            new_name='rank_النقاط',
        ),
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message',
        ),
        migrations.AddField(
            model_name='question',
            name='asnwer_choice_two_arabic_الإجابة_الثاني_عربى',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='asnwer_choice_two_english_الإجابة_الثاني_انجليزي',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='group_مجموعة',
            field=models.CharField(choices=[('Affinity', 'Affinity'), ('Collection of Information', 'Collection of Information'), ('Make decison', 'Make decison'), ('Time spending', 'Time spending')], default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_arabic_سؤال_الانجليزي',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_arabic_سؤال_عربي',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title_of_answer_choice_one_عنوان_الإجابة_الأول',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title_of_answer_choice_two_عنوان_الإجابة_الثاني',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
