# Generated by Django 4.0.6 on 2022-08-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0003_rename_question_arabic_question_asnwer_choice_one_arabic_الإجابة_الأولى_عربى_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_arabic_سؤال_الانجليزي',
            new_name='question_english_سؤال_الانجليزي',
        ),
    ]
