# Generated by Django 4.0.6 on 2022-08-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0004_rename_question_arabic_سؤال_الانجليزي_question_question_english_سؤال_الانجليزي'),
    ]

    operations = [
        migrations.CreateModel(
            name='tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Affinity_choice1', models.BigIntegerField()),
                ('Affinity_choice2', models.BigIntegerField()),
                ('Collection_of_Information_choice1', models.BigIntegerField()),
                ('Collection_of_Information_choice2', models.BigIntegerField()),
                ('Make_decison_choice1', models.BigIntegerField()),
                ('Make_decison_choice2', models.BigIntegerField()),
                ('Time_spending_choice1', models.BigIntegerField()),
                ('Time_spending_choice2', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
