# Generated by Django 4.0.6 on 2022-08-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0007_alter_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RIASEC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_مجموعة', models.CharField(choices=[('Realistic', 'Realistic'), ('Investigative', 'Investigative'), ('Artistic', 'Artistic'), ('Social', 'Social'), ('Enterprising', 'Enterprising'), ('Conventional', 'Conventional')], max_length=256)),
                ('rank_النقاط', models.BigIntegerField()),
                ('question_english_سؤال_الانجليزي', models.CharField(max_length=500)),
                ('question_arabic_سؤال_عربي', models.CharField(max_length=500)),
                ('asnwer_choice_one_english_الإجابة_الأولى_انجليزي', models.CharField(max_length=500)),
                ('asnwer_choice_one_arabic_الإجابة_الأولى_عربى', models.CharField(max_length=500)),
                ('asnwer_choice_two_english_الإجابة_الثاني_انجليزي', models.CharField(max_length=500)),
                ('asnwer_choice_two_arabic_الإجابة_الثاني_عربى', models.CharField(max_length=500)),
                ('answer_choice_three_english', models.CharField(max_length=500)),
                ('answer_choice_three_arabic', models.CharField(max_length=500)),
                ('answer_choice_four_english', models.CharField(max_length=500)),
                ('answer_choice_four_arabic', models.CharField(max_length=500)),
                ('answer_choice_five_english', models.CharField(max_length=500)),
                ('answer_choice_five_arabic', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='tally',
        ),
        migrations.AlterField(
            model_name='question',
            name='group_مجموعة',
            field=models.CharField(choices=[('Affinity', 'Affinity'), ('Collection of Information', 'Collection of information'), ('Make decison', 'Make decison'), ('Time spending', 'Time spending')], max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_of_answer_choice_one_عنوان_الإجابة_الأول',
            field=models.CharField(choices=[('Extrovert', 'Extrovert'), ('Sensing', 'Sensing'), ('Thinking', 'Thinking'), ('Judging', 'Judging')], max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_of_answer_choice_two_عنوان_الإجابة_الثاني',
            field=models.CharField(choices=[('Introvert', 'Introvert'), ('Intuition', 'Intuition'), ('Feeling', 'Feeling'), ('Perceiving', 'Perceiving')], max_length=256),
        ),
    ]
