# Generated by Django 4.0.6 on 2022-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0008_riasec_delete_tally_alter_question_group_مجموعة_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group_مجموعة',
            field=models.CharField(choices=[('Affinity', 'Affinity'), ('Collection of information', 'Collection of information'), ('Make decison', 'Make decison'), ('Time spending', 'Time spending')], max_length=256),
        ),
    ]
