# Generated by Django 4.0.6 on 2022-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0009_alter_question_group_مجموعة'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group_مجموعة',
            field=models.CharField(choices=[('Affinity', 'Affinity'), ('Collection of information', 'Collection of information'), ('Make decision', 'Make decision'), ('Time spending', 'Time spending')], max_length=256),
        ),
    ]
