# Generated by Django 4.0.6 on 2022-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0016_result_pdf_free_result_pdf_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_choice_change',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('affinity_Extrovert_to_Introvert', models.BigIntegerField()),
                ('affinity_Introvert_to_Extrovert', models.BigIntegerField()),
                ('collection_Sensing_to_Intuition', models.BigIntegerField()),
                ('collection_Intuition_to_Sensing', models.BigIntegerField()),
                ('make_Thinking_to_Feeling', models.BigIntegerField()),
                ('make_Feeling_to_Thinking', models.BigIntegerField()),
                ('time_Judging_to_Perceiving', models.BigIntegerField()),
                ('time_Perceiving_to_Judging', models.BigIntegerField()),
            ],
        ),
    ]
