# Generated by Django 4.0.6 on 2022-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0017_group_choice_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='report_purchase_successful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('four_letter_code', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=500)),
                ('user_email', models.CharField(max_length=500)),
                ('user_phone', models.CharField(max_length=500)),
                ('date_and_time_of_purchase', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='date_and_time_completed',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
