# Generated by Django 4.0.6 on 2022-10-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0019_remove_coupon_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
