# Generated by Django 4.0.6 on 2022-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0021_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='attempts_after_expiry',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='attempts_after_limit',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.CharField(max_length=500),
        ),
    ]
