# Generated by Django 4.0.6 on 2022-10-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0022_coupon_attempts_after_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
