# Generated by Django 4.0.6 on 2022-10-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0023_alter_coupon_expire_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
