# Generated by Django 4.0.6 on 2022-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0024_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(choices=[('name system', 'name system'), ('random number', 'random number'), ('custom name', 'custom name')], max_length=256)),
                ('code', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('expire_date', models.DateField()),
                ('usage_limit', models.CharField(max_length=500)),
                ('attempts_after_limit', models.CharField(max_length=500)),
                ('attempts_after_expiry', models.CharField(max_length=500)),
            ],
        ),
    ]
