# Generated by Django 4.0.6 on 2022-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0025_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='attempts_after_expiry',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='attempts_after_limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.BigIntegerField(),
        ),
    ]
