# Generated by Django 4.0.6 on 2022-10-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0026_alter_coupon_attempts_after_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='attempts_after_expiry',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='attempts_after_limit',
        ),
    ]
