# Generated by Django 4.0.6 on 2023-03-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0030_report_purchase_successful_id_result_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marketers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=500)),
                ('user_email', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('number_of_visits', models.BigIntegerField(default=0)),
                ('number_of_free_downloads', models.BigIntegerField(default=0)),
                ('number_of_paid_downloads', models.BigIntegerField(default=0)),
                ('paypal_link', models.CharField(max_length=500)),
                ('amount_earned', models.FloatField(default=0)),
            ],
        ),
    ]
