# Generated by Django 4.0.6 on 2023-03-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0031_marketers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketers',
            name='id',
        ),
        migrations.AlterField(
            model_name='marketers',
            name='member_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
