# Generated by Django 4.0.6 on 2023-03-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0032_remove_marketers_id_alter_marketers_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketers',
            old_name='link',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='marketers',
            old_name='paypal_link',
            new_name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='marketers',
            name='user_email',
        ),
    ]
