# Generated by Django 4.0.6 on 2023-03-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0033_rename_link_marketers_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketers',
            name='link',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
