# Generated by Django 4.0.6 on 2023-03-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0034_marketers_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketers',
            name='user_email',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
