# Generated by Django 4.0.6 on 2023-03-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0036_marketers_number_of_receipt_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketers',
            name='number_of_paymnents',
            field=models.BigIntegerField(default=0),
        ),
    ]
