# Generated by Django 4.0.6 on 2023-03-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0037_marketers_number_of_paymnents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketers',
            old_name='number_of_paymnents',
            new_name='number_of_payments',
        ),
    ]
