# Generated by Django 4.0.6 on 2023-03-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survery_app', '0038_rename_number_of_paymnents_marketers_number_of_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_purchase_successful',
            name='success_code',
            field=models.BigIntegerField(default=0),
        ),
    ]
